### ISSUE TITLE
PDF utility is causing error on deployment 

### ISSUE THREAD

**Issue by cawooda** [cawooda/circle#17]
server/utils/pdfUtility.js

This code is causing an error in render. It seems most pdf converters rely on headless browsers and its search for Chromium is fruitless so it goes red.

Error generating PDF: Error: Could not find Chrome (ver. 127.0.6533.88). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: /opt/render/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (/opt/render/project/src/server/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:291:27)
    at ChromeLauncher.executablePath (/opt/render/project/src/server/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:209:25)
    at ChromeLauncher.computeLaunchArguments (/opt/render/project/src/server/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:89:37)
    at async ChromeLauncher.launch (/opt/render/project/src/server/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:70:28)
    at async convertToPdf (/opt/render/project/src/server/utils/pdfUtility.js:17:21)
    at async Object.signServiceAgreement (/opt/render/project/src/server/schemas/resolvers.js:168:25)
Error in signServiceAgreement: Error: Failed to generate PDF
![IMG_0368](https://github.com/user-attachments/assets/6bd71c31-f8be-434a-a551-f813a3bdb39b)

**Comment by cawooda** [comment]
This might help but I don't understand how to implement it:

https://community.render.com/t/installing-headless-chromium-w-o-docker/5185/2
